baseURL = "https://c01dc0ffee.github.io/"
languageCode = "en-us"
title = "c01dc0ffee.github.io"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableEmoji = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
